FROM ubuntu
RUN apt-get update && \
    apt install -y python3 && \
    apt-get install -y python3-pip && \
    apt-get install -y git && \
    apt install -y vim && \
    pip3 install --upgrade setuptools && \
    pip3 install --upgrade ansible && \
    alias python=python3

RUN mkdir -p /apps/data/container
RUN mkdir -p /apps/code/
ADD create_file.py /apps/code/
RUN git config --global user.email "tripathi.vineetbaba@gmail.com"
RUN git config --global user.name "tripathi-vineetbaba"
ENTRYPOINT ["python3","/apps/code/create_file.py"]
RUN ansible --version 
ENTRYPOINT ["/bin/bash"]

