FROM ubuntu
RUN apt-get update && \
    apt install -y python3 && \
    apt install -y vim && \
    alias python=python3

RUN mkdir -p /apps/data/container
RUN mkdir -p /apps/code/
ADD create_file.py /apps/code/
ENTRYPOINT ["python3","/apps/code/create_file.py"]
ENTRYPOINT ["/bin/bash"]
